# Generated by Django 6.1 on 2026-08-23 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("institution", models.CharField(max_length=100)),
                ("sort_code", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("currency", models.CharField(default="GBP", max_length=3)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatementUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSED", "Processed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("rows", models.IntegerField(blank=True, null=True)),
                ("file", models.FileField(upload_to="statements/")),
                ("error_message", models.TextField(blank=True)),
                ("parser", models.CharField(blank=True, max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_uploads",
                        to="transactions.account",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statement_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("merchant", models.CharField(blank=True, max_length=100)),
                ("bank_reference", models.CharField(blank=True, max_length=100)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("CASH_WITHDRAWAL", "Cash Withdrawal"),
                            ("STANDING_ORDER", "Standing Order"),
                            ("DEBIT", "Debit"),
                            ("CREDIT", "Credit"),
                            ("CARD_PURCHASE", "Card Purchase"),
                            ("DIRECT_DEBIT", "Direct Debit"),
                            ("TRANSFER", "Transfer"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("posted_date", models.DateField()),
                ("transaction_date", models.DateField(blank=True, null=True)),
                ("description", models.CharField(max_length=255)),
                ("fingerprint", models.CharField(max_length=64)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="transactions.account",
                    ),
                ),
                (
                    "statement_upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="transactions.statementupload",
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_account_name_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("user", "sort_code", "account_number"),
                name="unique_bank_account_per_user",
            ),
        ),
        migrations.AddIndex(
            model_name="statementupload",
            index=models.Index(
                fields=["account", "uploaded_at"], name="transaction_account_0fca36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["account", "posted_date"], name="transaction_account_1b15a5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                fields=("account", "fingerprint"), name="unique_transaction_fingerprint"
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                fields=("account", "external_id"), name="unique_transaction_external_id"
            ),
        ),
    ]
