# Generated by Django 6.1 on 2026-09-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_category_transaction_category_categoryrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="category_is_manual",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="categoryrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("pattern__regex", "\\S")),
                name="categoryrule_pattern_not_blank",
            ),
        ),
    ]
