# Generated by Django 6.1 on 2026-09-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0006_category_user_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoryrule",
            name="source",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("LLM", "LLM")],
                default="MANUAL",
                max_length=10,
            ),
        ),
    ]
