# Generated by Django 6.1 on 2026-09-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0007_categoryrule_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="kind",
            field=models.CharField(
                choices=[
                    ("SPEND", "Spend"),
                    ("INCOME", "Income"),
                    ("TRANSFER", "Transfer"),
                    ("SAVING", "Saving"),
                ],
                default="SPEND",
                max_length=20,
            ),
        ),
    ]
